on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Windows Build", os: ubuntu-latest, build: "x86_64-linux" }
          - { name: "Linux Build",  os: ubuntu-latest, build: "x86_64-windows" }

    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1

      - name: Install Vulkan SDK
        uses: ThomasAunvik/install-vulkan-sdk-action@f033a80daddd8b0bb9ad509807ef5b7963988b8e
        with:
          vulkan_version: 1.3.290.0
          install_runtime: true
          cache: true
          stripdown: true

      - name: Build
        run: zig build -Dtarget=${{ matrix.config.build }}

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.config.build }}
          path: zig-out/bin/